### ISSUE TITLE
Libraries to add in next iteration

### ISSUE THREAD

**Issue by darribas** [darribas/gds_env#25]
To add:

- [x] [`eo-learn`](https://github.com/sentinel-hub/eo-learn) (added in b1a16dc)
- [x] [`pygeoda`](https://github.com/lixun910/pygeoda) (added in 5409c0bdbff4e94da25fc58fd50fe5a34cf0140e)
- [x] [`jekyll`](https://jekyllrb.com/)
- [x] [`bookdown`](https://github.com/rstudio/bookdown)
- [x] `ipympl` (added in ecf4e36)
- [x] [`kableExtra`](https://github.com/haozhu233/kableExtra) (added in 64d48ed)

To explore experimentally:

- [x] [~`spatialite`~](https://www.gaia-gis.it/fossil/libspatialite/wiki?name=SpatiaLite) (and some bridge to python) (see [this issue](https://github.com/jGaboardi/geopackage_tutorial/issues/1) for context, but turns out `libspatialite` [already comes in `3.0`](https://github.com/darribas/gds_env/blob/master/stack_py.txt#L146))

To consider removing:

- [x] Bayesian libraries (`pymc3`, `pystan`, `bambino`), on the basis they might be taking quite a bit of space and have not been used in the last releases.  (removed in b1a16dc)

**Comment by iamwfx** [comment]
Hi Dani thanks for creating/maintaining this! It's been a lifesaver for working on a shared cluster. :) 

Some minor things if you plan update libraries: 
- `datashader` v 0.9.0 has some new transfer functions. 
- Also, the latest version of `dask` (v 2.9.0) allows you to visualize task graphs, which can be useful.

**Comment by darribas** [comment]
Very nice to hear you're finding it useful! Thanks very much for the suggestions! Yes, both `datashader` and `dask` and on the "list" so, when I re-build for `gds:4.0`, they should get an update. My timeline usually follows PySAL releases so, after the January release is shipped, I'll roll out a new version, which should have those updates.

**Comment by darribas** [comment]
Just a quick ping to @iamwfx that the new version (4.0) is out and includes updated version of `dask` and `datashader` (as well as the new, related project `spatialpandas`). Happy to get any feedback if you run into issues!
