### ISSUE TITLE
consider tectonic

### ISSUE THREAD

**Issue by knaaptime** [darribas/gds_env#28]
it probably doesnt matter too much, fwiw but you might be able to trim the container size a bit by using [tectonic](https://tectonic-typesetting.github.io/en-US/) instead of a full latex distribution. I switched [mandown](https://github.com/knaaptime/mandown) over about a month ago and it's working really nicely (admitedly, the goals in mandown are slightly different, since i need everything to be conda-installable, but still thought it might be worth considering).

**Comment by darribas** [comment]
Nice! tectonic might be a good option but I haven't spent much time on the LaTeX part, I use mostly what comes from the official `jupyter` image I build off of. Good to keep in mind though, might try to run some experiments at some point to see what the changes would be...

**Comment by darribas** [comment]
Closing for now but consider reopening if there's further discussion. I've decided, since LaTeX is currently provided to `gds_env` through the upstream `minimal-notebook`, I'd rather leave it as is.
