### ISSUE TITLE
Worth including a preview of `geopandas.view`?

### ISSUE THREAD

**Issue by darribas** [darribas/gds_env#61]
If there's a pre-version (maybe installing from `master`) that could go into `6.1` it'd be great to ship with 6.1 as "experimental".

Tagging @martinfleis to confirm either way. If not fully ready, this can go to `7.0`

**Comment by martinfleis** [comment]
Installing from master (main) will be the best. 90% of stuff is in.

**Comment by darribas** [comment]
OK I've just added the repo without pinning to any particular branch/commit, but for the release I'll add the commit version so it's reproducible easily...
