### ISSUE TITLE
Jupyterlab freezing with Safari after password screen

### ISSUE THREAD

**Issue by TerryLines** [darribas/gds_env#66]
I have GDS_py 6.1 running on docker within an AWS instance. I can access jupyterlab without problems with Firefox and Chrome, however when using Safari (Version 14.1.2 (16611.3.10.1.6)), the token or password is accepted but then the screen pauses.

Javascript console highlighted the following errors.
<img width="1260" alt="Screenshot 2021-09-03 at 21 12 18" src="https://user-images.githubusercontent.com/43879942/132064690-c827f4f2-f959-4637-91d3-87c8566302f3.png">

**Comment by martinfleis** [comment]
I am not sure that this is something we can fix on our side. There will be a new version of the container in about a month, including the latest Jupyter Lab so that may fix this issue. If not, it may be something to report to the JLab repository.
