### ISSUE TITLE
GDS_ENV_VERSION not working in gds_dev

### ISSUE THREAD

**Issue by martinfleis** [darribas/gds_env#67]
`gds_dev:6.1` does not have the environment variable GDS_ENV_VERSION.

![Screenshot 2021-09-06 at 10 13 59](https://user-images.githubusercontent.com/36797143/132192236-dcffb72d-45d5-4edf-b64a-823e80510a4c.png)

**Comment by darribas** [comment]
This is related to the `GDS_ENV_VERSION` variable being created as `jovyan`. Explore creating it as `root`:

https://github.com/darribas/gds_env/blob/36168342d5a920955080b772c472245062b3e1e0/gds_py/Dockerfile#L134-L138
