### ISSUE TITLE
ERROR 1: on geopandas import in version 8

### ISSUE THREAD

**Issue by sjsrey** [darribas/gds_env#77]
`ERROR 1: PROJ: proj_create_from_database: Open of /opt/conda/share/proj failed`

is thrown on import geopandas in a fresh GDS_ENV version 8.0.

This does not seem to be fatal, as subsequent geopandas calls seem to work fine.

**Comment by darribas** [comment]
Sorry I never replied to this. Yes, I've noticed this issues too but I haven't had any tangible effect on runtime so I did not pay much attention. I'm hoping with [9.0](https://github.com/darribas/gds_env/issues/76) this gets automatically resolved. Closing for now but happy to engage further if anything comes up.
